### ISSUE TITLE
refactor(ui): improve structure project

### ISSUE THREAD

**Issue by ronz204** [rruiz204/pets-and-paws-client#1]
### Tasks

- [x] Login Page UI and Data Fetching
- [x] Forgot Page UI and Data Fetching
- [x] Reset Page UI and Data Fetching
- [x] Khaos Hook and Specific Hooks
- [x] Format Khaos Responses
- [x] Centralize hooks in Core
- [x] Create Authentication Guard
- [x] Navigation bar with RBAC
- [x] Improve Structures: assets, modules & components
- [x] Refactor in Data Fetching (khaos, hooks & stores)
- [x] Improve the consistency of Khaos
